# Generated by Django 4.2.30 on 2026-04-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(help_text="Il messaggio inviato dall'utente", verbose_name='Messaggio Utente')),
                ('bot_response', models.TextField(help_text="La risposta generata dall'assistente AI", verbose_name='Risposta Bot')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data e Ora')),
                ('session_id', models.CharField(blank=True, help_text='Identificativo sessione utente (futuro)', max_length=255, null=True, verbose_name='ID Sessione')),
                ('response_time_ms', models.IntegerField(default=0, help_text='Tempo impiegato per generare la risposta', verbose_name='Tempo Risposta (ms)')),
                ('ai_provider', models.CharField(default='mock', help_text='Il provider AI utilizzato (mock, openai, etc.)', max_length=50, verbose_name='Provider AI')),
            ],
            options={
                'verbose_name': 'Log Chat',
                'verbose_name_plural': 'Log Chat',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session_id', 'timestamp'], name='chatbot_cha_session_1a2965_idx')],
            },
        ),
    ]
