# Generated by Django 4.2.30 on 2026-04-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nome Prodotto')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prezzo (€)')),
                ('available', models.BooleanField(db_index=True, default=True, verbose_name='Disponibile')),
                ('category', models.CharField(choices=[('farmaco', 'Farmaco'), ('integratore', 'Integratore'), ('cosmetico', 'Cosmetico'), ('dispositivo', 'Dispositivo Medico'), ('igiene', 'Igiene Personale'), ('altro', 'Altro')], db_index=True, default='farmaco', max_length=20, verbose_name='Categoria')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Codice SKU')),
                ('requires_prescription', models.BooleanField(default=False, verbose_name='Richiede Ricetta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Inserimento')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo Aggiornamento')),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'available'], name='pharmacy_pr_categor_bce674_idx'), models.Index(fields=['name', 'available'], name='pharmacy_pr_name_a6c2f5_idx')],
            },
        ),
    ]
